### ISSUE TITLE
track destroyed units and statics

### ISSUE THREAD

**Issue by mac-developer** [AGluttonForPunishment/SPGG#1]
Thanks for your job! It is a great script which works fine! Thanks.

One question,

Is there some way to save Mission Editor Groups destroyed during the dcs mission?

Script always respawn even they've been destroyed.

**Comment by AGluttonForPunishment** [comment]
Hi, the script only saves "active" and "alive" units/static.

1. Option: Your issue might be a save is not running after the units are destroyed.
See the timer for scheduled saving (default every 60 min). Or you can run the save command manually from a trigger in ME or your own scripts. (Se the readme for available functions)

2. Option: Units that are placed in the ME need to be "Late activation" and only be activated if the mission is not loaded in a persistent state.
See the the last trigger in the example Miz files provided for how to do this.
(FLAG (spgginitalstart) and global script variable (spgg.initalstart) to detect if mission has loaded a save file)


Also static objects are not saved at the moment in DCS Open Beta because of this bug:
https://forum.dcs.world/topic/124151-known-scripting-engine-issues/?do=findComment&comment=5170313
